name: Node.js Package

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master
      - 'release-*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.3
      - run: npm ci --progress=false && npm run line:build && npm run monochrome:build
        env:
          API_DOWNLOAD_LINE: ${{ secrets.API_DOWNLOAD_LINE }}
          API_DOWNLOAD_MONOCHROME: ${{ secrets.API_DOWNLOAD_MONOCHROME }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: primer/publish@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
