name: Update Icons

on: 
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.16.3
      - name: Download & Build Icons
        run: npm ci --progress=false && npm run line:build && npm run monochrome:build
        env:
          CI_COMMIT_REF_NAME: ${{ steps.extract_branch.outputs.branch }}
          API_DOWNLOAD_LINE: ${{ secrets.API_DOWNLOAD_LINE }}
          API_DOWNLOAD_MONOCHROME: ${{ secrets.API_DOWNLOAD_MONOCHROME }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Updated icons/build scripts